package com.tn.sonede.persistance;

// Generated 31 mars 2014 16:08:34 by Hibernate Tools 3.4.0.CR1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Personnel generated by hbm2java
 */
@Entity
@Table(name = "agent", catalog = "public")
public class Agent implements java.io.Serializable {

	private int matricule;
	private String nom;
	private String prenom;
	private Structure structure;
	

	public Agent() {
	}

	public Agent(int matricule) {
		this.matricule = matricule;
	}

	public Agent(int matricule, String nom, String prenom, Structure structure) {
		this.matricule = matricule;
		this.nom = nom;
		this.prenom = prenom;
		this.structure=structure;
	}

	@Id
	@Column(name = "matricule", unique = true, nullable = false)
	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}



	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_struc")
	public Structure getStructure() {
		return this.structure;
	}

	public void setStructure(Structure structure) {
		this.structure = structure;
	}

	@Override
	public String toString() {
		return matricule+"";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		
		result = prime * result + (int) (matricule ^ (matricule >>> 32));
		
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Agent other = (Agent) obj;
		
		if (matricule != other.matricule)
			return false;
		
		
		return true;
	}

	

}
